   name: Build APK

   on:
     push:
       branches:
         - main

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
       - name: Check out the code
         uses: actions/checkout@v2

       - name: Set up JDK
         uses: actions/setup-java@v1
         with:
           java-version: 17

       - name: Build project and generate APK
         run: |
           # Add your build commands here
           ./gradlew assembleRelease
           
