name: Build and Release APK

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: windows-latest

    env:
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r26c
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up NDK
        run: |
          $ndkFile = 'android-ndk-r26c-windows.zip'
          $ndkUrl = 'https://dl.google.com/android/repository/android-ndk-r26c-windows.zip'
          Invoke-WebRequest -Uri $ndkUrl -OutFile $ndkFile
          Expand-Archive -Path $ndkFile -DestinationPath $env:ANDROID_NDK_HOME

      - name: Set up LLVM
        run: choco upgrade llvm

      - name: Set up Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v2

      - name: Install MinGW
        run: choco install mingw

      - name: Install dependencies
        run: |
          choco install cmake
          choco install ninja
          choco install git
      
      - name: Build APK
        run: |
          cd cosmic-station\cosmic-station\src\android
          .\gradlew.bat assembleRelease
        env:
          ALLOW_EXTERNAL_SPIRV_TOOLS: ON

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: src/app/build/outputs/apk/release/app-release.apk
